# Generated by cpp11: do not edit by hand

input_requirement_ <- function(Xr, dr) {
  .Call(`_leontief_input_requirement_`, Xr, dr)
}

augmented_input_requirement_ <- function(Xr, wr, cr, dr) {
  .Call(`_leontief_augmented_input_requirement_`, Xr, wr, cr, dr)
}

output_allocation_ <- function(Xr, dr) {
  .Call(`_leontief_output_allocation_`, Xr, dr)
}

leontief_inverse_ <- function(Ar) {
  .Call(`_leontief_leontief_inverse_`, Ar)
}

equilibrium_output_ <- function(Lr, dr) {
  .Call(`_leontief_equilibrium_output_`, Lr, dr)
}

output_multiplier_ <- function(Lr) {
  .Call(`_leontief_output_multiplier_`, Lr)
}

income_multiplier_ <- function(Lr, wr) {
  .Call(`_leontief_income_multiplier_`, Lr, wr)
}

employment_multiplier_ <- function(Lr, er) {
  .Call(`_leontief_employment_multiplier_`, Lr, er)
}

employment_number_ <- function(Lr, er, cr) {
  .Call(`_leontief_employment_number_`, Lr, er, cr)
}

backward_linkage_ <- function(Ar) {
  .Call(`_leontief_backward_linkage_`, Ar)
}

forward_linkage_ <- function(Ar) {
  .Call(`_leontief_forward_linkage_`, Ar)
}

power_dispersion_ <- function(Lr) {
  .Call(`_leontief_power_dispersion_`, Lr)
}

power_dispersion_cv_ <- function(Lr) {
  .Call(`_leontief_power_dispersion_cv_`, Lr)
}

sensitivity_dispersion_ <- function(Lr) {
  .Call(`_leontief_sensitivity_dispersion_`, Lr)
}

sensitivity_dispersion_cv_ <- function(Lr) {
  .Call(`_leontief_sensitivity_dispersion_cv_`, Lr)
}

multiplier_product_matrix_ <- function(Lr) {
  .Call(`_leontief_multiplier_product_matrix_`, Lr)
}
