# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

input_requirement_matrix <- function(X, d) {
    .Call(`_inputoutput_input_requirement_matrix`, X, d)
}

output_allocation_matrix <- function(X, d) {
    .Call(`_inputoutput_output_allocation_matrix`, X, d)
}

leontief_inverse <- function(A) {
    .Call(`_inputoutput_leontief_inverse`, A)
}

ghosh_inverse <- function(B) {
    .Call(`_inputoutput_ghosh_inverse`, B)
}

