# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Input requirement matrix
#' @param X input-output matrix
#' @param d final demand vector
#' @examples
#' set.seed(200100)
#' X <- matrix(rnorm(100), nrow = 10)
#' d <- rnorm(10)
#' input_requirement_matrix(X,d)
#' @export
input_requirement_matrix <- function(X, d) {
    .Call('_inputoutput_input_requirement_matrix', PACKAGE = 'inputoutput', X, d)
}

#' Output allocation matrix
#' @param X input-output matrix
#' @param d final demand vector
#' @examples
#' set.seed(200100)
#' X <- matrix(rnorm(100), nrow = 10)
#' d <- rnorm(10)
#' output_allocation_matrix(X,d)
#' @export
output_allocation_matrix <- function(X, d) {
    .Call('_inputoutput_output_allocation_matrix', PACKAGE = 'inputoutput', X, d)
}

#' Leontief inverse matrix
#' @param A input requirement matrix
#' @examples
#' set.seed(200100)
#' A <- matrix(rnorm(100), nrow = 10)
#' leontief_inverse(A)
#' @export
leontief_inverse <- function(A) {
    .Call('_inputoutput_leontief_inverse', PACKAGE = 'inputoutput', A)
}

#' Ghosh inverse matrix
#' @param B output allocation matrix
#' @examples
#' set.seed(200100)
#' B <- matrix(rnorm(100), nrow = 10)
#' leontief_inverse(B)
#' @export
ghosh_inverse <- function(B) {
    .Call('_inputoutput_ghosh_inverse', PACKAGE = 'inputoutput', B)
}

