# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Input requirement
#' @param X transaction matrix
#' @param d final demand vector
#' @examples
#' set.seed(200100)
#' X <- matrix(rnorm(100), nrow = 10)
#' d <- rnorm(10)
#' input_requirement(X,d)
#' @export
input_requirement <- function(X, d) {
    .Call('_inputoutput_input_requirement', PACKAGE = 'inputoutput', X, d)
}

#' Output allocation
#' @param X transaction matrix
#' @param d final demand vector
#' @examples
#' set.seed(200100)
#' X <- matrix(rnorm(100), nrow = 10)
#' d <- rnorm(10)
#' output_allocation(X,d)
#' @export
output_allocation <- function(X, d) {
    .Call('_inputoutput_output_allocation', PACKAGE = 'inputoutput', X, d)
}

#' Leontief inverse
#' @param A input requirement matrix
#' @examples
#' set.seed(200100)
#' A <- matrix(rnorm(100), nrow = 10)
#' leontief_inverse(A)
#' @export
leontief_inverse <- function(A) {
    .Call('_inputoutput_leontief_inverse', PACKAGE = 'inputoutput', A)
}

#' Ghosh inverse
#' @param B output allocation matrix
#' @examples
#' set.seed(200100)
#' B <- matrix(rnorm(100), nrow = 10)
#' leontief_inverse(B)
#' @export
ghosh_inverse <- function(B) {
    .Call('_inputoutput_ghosh_inverse', PACKAGE = 'inputoutput', B)
}

#' Equilibrium output
#' @param L Leontief inverse matrix
#' @param d final demand vector
#' @examples
#' set.seed(200100)
#' L <- matrix(rnorm(100), nrow = 10)
#' d <- rnorm(10)
#' equilibrium_output(L,d)
#' @export
equilibrium_output <- function(L, d) {
    .Call('_inputoutput_equilibrium_output', PACKAGE = 'inputoutput', L, d)
}

#' Output multiplier
#' @param L Leontief inverse matrix
#' @examples
#' set.seed(200100)
#' L <- matrix(rnorm(100), nrow = 10)
#' output_multiplier(L)
#' @export
output_multiplier <- function(L) {
    .Call('_inputoutput_output_multiplier', PACKAGE = 'inputoutput', L)
}

#' Household income multiplier
#' @param L Leontief inverse matrix
#' @param w wage vector
#' @export
household_income_multiplier <- function(L, w) {
    .Call('_inputoutput_household_income_multiplier', PACKAGE = 'inputoutput', L, w)
}

#' Income multiplier
#' @param L Leontief inverse matrix
#' @param w wage vector
#' @export
income_multiplier <- function(L, w) {
    .Call('_inputoutput_income_multiplier', PACKAGE = 'inputoutput', L, w)
}

#' Employment multiplier
#' @param L Leontief inverse matrix
#' @param e employment vector
#' @export
employment_multiplier <- function(L, e) {
    .Call('_inputoutput_employment_multiplier', PACKAGE = 'inputoutput', L, e)
}

#' Input multiplier
#' @param G Ghosh inverse matrix
#' @examples
#' set.seed(200100)
#' G <- matrix(rnorm(100), nrow = 10)
#' output_multiplier(G)
#' @export
input_multiplier <- function(G) {
    .Call('_inputoutput_input_multiplier', PACKAGE = 'inputoutput', G)
}

#' Backward linkage
#' @param L Leontief inverse matrix
#' @export
backward_linkage <- function(L) {
    .Call('_inputoutput_backward_linkage', PACKAGE = 'inputoutput', L)
}

#' Backward linkage coefficient of variation
#' @param L Leontief inverse matrix
#' @export
backward_linkage_cv <- function(L) {
    .Call('_inputoutput_backward_linkage_cv', PACKAGE = 'inputoutput', L)
}

#' Forward linkage
#' @param L Leontief inverse matrix
#' @export
forward_linkage <- function(L) {
    .Call('_inputoutput_forward_linkage', PACKAGE = 'inputoutput', L)
}

#' Forward linkage coefficient of variation
#' @param L Leontief inverse matrix
#' @export
forward_linkage_cv <- function(L) {
    .Call('_inputoutput_forward_linkage_cv', PACKAGE = 'inputoutput', L)
}

#' Multiplier product matrix
#' @param L Leontief inverse matrix
#' @export
multiplier_product_matrix <- function(L) {
    .Call('_inputoutput_multiplier_product_matrix', PACKAGE = 'inputoutput', L)
}

